services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: busfahrt_app
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-container
    ports:
      - "8080:80"
      - "8443:443"
    # keep logs/ssl mounts so you can adjust certs/logs without rebuilding
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl/:/etc/nginx/ssl/
    depends_on:
      - mysql
      - node

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - START_SERVER_AFTER_DOCS=1
    command: sh -c "npm install && npm start"
    
volumes:
  mysql_data: