services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: busfahrt_app
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    container_name: nginx-container

    ports:
      - "8080:3080"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./frontend/public/:/usr/share/nginx/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysql

  node:
    image: node:latest
    container_name: node-container

    ports:
      - "3000:3000"
    volumes:
    - ./backend/:/usr/src/app/
    working_dir: /usr/src/app/
    depends_on:
      - mysql
    command: sh -c "npm install && npm start"